service: ffm-bref
variablesResolutionMode: 20210326
custom:
  currentStage: ${opt:stage, self:provider.stage}
  localstack: #TODO: 
    stages: #TODO: set which stages to use localstack
      - local  
    host: http://192.168.208.177  #TODO: set LocalStack host to connect to by running ipconfig in your machine
    edgePort: 45660  #TODO: set LocalStack edge port to connect to, default 4566
    autostart: false  #TODO: set true to Start LocalStack in Docker on Serverless deploy if NOT using devcontainer
    #TODO: Run Localstack as separate docker when using devcontainers, therefore "autostart: false" must be set
    # docker run --rm -it -p 45660:4566 localstack/localstack -e "SERVICES=rds,s3,elasticache,lambda" -e "EDGE_PORT=45660"
    lambda:
      mountCode: False #TODO: Set this flag to True improve performance when mounting Lambda code
    docker:
      sudo: False #TODO: Set this flag to True run "docker ..." commands as sudo, also if "autostart: true" is set. 

provider:
    name: aws
    region: ap-southeast-2
    runtime: provided.al2
    profile: devel
    stage: devel
    lambdaHashingVersion: 20201221
    environment: ${file(./serverless-include/environment/${self:custom.currentStage}.environment.yml)}

plugins:
    - ./vendor/bref/bref
    - ./vendor/bref/extra-php-extensions
    - serverless-localstack

functions:
    - ${file(./serverless-include/function/${self:custom.currentStage}.function.yml)}
    
# Exclude files from deployment
package:
    patterns:
        - '!node_modules/**'
        - '!tests/**'
        - '!README.md'
        - '!setup.sh'
        - '!package.json'
        - '!package-lock.json'
        - '!composer.json'
        - '!composer.phar'
        - '!composer.lock'
        - '!serverless-include/**'