BREF_PING_DISABLE: 1 #disable bref ping stats
API_HOST: ${ssm:/API/config/API_HOST,"ifconfig.me"}

#TODO: fetch prod ssm secret values and export it to environment
DB_CRM_PASS: ${ssm:/DB/credentials/DB_CRM_PASS,"null"}
DB_CRM_USER: ${ssm:/DB/credentials/DB_CRM_USER,"null"}
DB_CRM_SERV: ${ssm:/DB/credentials/DB_CRM_SERV,"null"}
DB_CRM_NAME: ${ssm:/DB/credentials/DB_CRM_NAME,"null"}